# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_examinee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ex_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ex_time_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ClassRoom'),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='ex_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprofile',
            name='ex_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
