# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20230703_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='quizprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
        ),
    ]
